/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUI;

import JPWord.Data.*;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dialog;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author u0151316
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        //File file = new File("C:\\Users\\u0151316\\Documents\\JP\\Dictionary.dat");
        Database.getInstance().initialize("C:\\Users\\u0151316\\Documents\\JP\\Dictionary.dat");
        //Database.getInstance().initialize("C:\\Users\\u0151316\\Documents\\Visual Studio 2010\\Projects\\JPWord\\JPWord\\bin\\Debug\\Dictionary_test.dat");
        initComponents();
        editPanel1.initialize();
        rememberPanel1.initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMainTabbedPane = new javax.swing.JTabbedPane();
        rememberPanel1 = new MainUI.RememberPanel();
        editPanel1 = new MainUI.EditPanel();
        databasePanel3 = new MainUI.DatabasePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPWord");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMainTabbedPane.setAlignmentX(0.0F);
        jMainTabbedPane.setAlignmentY(0.0F);
        jMainTabbedPane.setMinimumSize(new java.awt.Dimension(740, 430));
        jMainTabbedPane.setName(""); // NOI18N
        jMainTabbedPane.setPreferredSize(new java.awt.Dimension(740, 430));
        jMainTabbedPane.addTab("Remember", rememberPanel1);
        jMainTabbedPane.addTab("  Edit  ", editPanel1);
        jMainTabbedPane.addTab("Database", databasePanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMainTabbedPane.getAccessibleContext().setAccessibleName("tab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.out.println("jp.MainFrame.formWindowClosing()");
        Database.getInstance().getDatabase().save();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MainUI.DatabasePanel databasePanel3;
    private MainUI.EditPanel editPanel1;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private MainUI.RememberPanel rememberPanel1;
    // End of variables declaration//GEN-END:variables
}
