/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUI;

import JPWord.Data.IWord;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author u0151316
 */
public class ImportDialog extends javax.swing.JDialog {

    public boolean isOK_ = false;

    /**
     * Creates new form ImportDialog
     */
    public ImportDialog(java.awt.Frame parent, boolean modal, List<String[]> items) {
        super(parent, modal);
        initComponents();

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Word");
        dtm.addColumn("kana");
        dtm.addColumn("Type");
        dtm.addColumn("Mean");
        dtm.addColumn("Other");
        dtm.addColumn("Status");
        try {
            for (String[] item : items) {
                if (item[0].equals("[DUP]")) {
                    continue;
                }
                if (item.length < 5) {
                    //error
                    dtm.addRow(new Object[]{"", "", "", "", "", "[ERR]"});
                } else {
                    String w = item[0];
                    String k = "";
                    if (item[1].equals("")) {
                        k = item[0];
                    } else {
                        k = item[1];
                    }
                    String status = "";
                    for (IWord word : Database.getInstance().getDatabase().getWords()) {
                        if (word.getContent().equals(k) && word.getKana().equals(w) && word.getTone().equals(item[2])) {
                            status = "[DUP]";
                        }
                    }

                    if (item.length > 5) {
                        dtm.addRow(new Object[]{w, k, item[2], item[3], item[4], status + " [???]"});
                    } else {
                        dtm.addRow(new Object[]{w, k, item[2], item[3], item[4], status});
                    }
                }
            }
        } catch (Exception e) {
        }

        jTable1.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnOK = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(680, 447));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 620, 340);

        jbtnOK.setText("OK");
        jbtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOKActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnOK);
        jbtnOK.setBounds(440, 360, 51, 25);

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCancel);
        jbtnCancel.setBounds(540, 360, 73, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        // TODO add your handling code here:
        isOK_ = false;
        this.setVisible(false);
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOKActionPerformed
        // TODO add your handling code here:
        isOK_ = true;
        this.setVisible(false);
    }//GEN-LAST:event_jbtnOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnOK;
    // End of variables declaration//GEN-END:variables
}
